replicaCount: 1

image:
  repository: registry.macnolo.net/website
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: www.macnolo.net
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: macnolo.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: 
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
