apiVersion: v1
kind: Service
metadata:
  name: "website-service"
  labels:
    app: "website"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: "website"
